### ISSUE TITLE
Compile issue with ncs v1.6.1

### ISSUE THREAD

**Issue by jeback1** [too1/ncs-peripheral-uart-adc#1]
UPDATE: The issue appears to be caused by changes to Zephyr's logging subsystem. When calling LOG_INF with a pointer parameter (%p) the pointer should be cast to a void pointer. With the following two changes, I am able to build with ncs v1.6.1:
`	LOG_INF("Numeric Match, conn %p", auth_conn);`  at line 460 changed to
`	LOG_INF("Numeric Match, conn %p", (void *)auth_conn);`
and
`	LOG_INF("Numeric Reject, conn %p", auth_conn);` at line 463 changed to
`	LOG_INF("Numeric Reject, conn %p", (void *)auth_conn);`

ORIGINAL MESSAGE:
I'm unable to build it under ncs v1.6.1. My board is the nrf52840dk. 

I am able to build and flash ~/ncs/nrf/samples/bluetooth/peripheral_uart. I was successful in building another of your samples: ncs-uart-async-count-rx.  I also cloned it into ~/ncs/nrf/samples/bluetooth and had no warnings or errors when building for nrf52840dk.

I've pasted the output with the first error at the bottom. There are additional warnings about deprecated declarations and many repetitions of the error message regarding 'cbprintf_internal.h:88:15: error: invalid use of undefined type 'struct bt_conn''.  

Could this be an issue with the version of ncs?
Thanks,
Jan Erik

FAILED: CMakeFiles/app.dir/src/main.c.obj
ccache /opt/gnuarmemb/bin/arm-none-eabi-gcc -DBUILD_VERSION=v2.6.0-rc1-ncs1-3-g0944459b5b62 -DKERNEL -DNRF52840_XXAA -DUSE_PARTITION_MANAGER=0 -D_FORTIFY_SOURCE=2 -D__PROGRAM_START -D__ZEPHYR__=1 -I../. -I/home/k/ncs/nrf/drivers/mpsl/clock_control -I/home/k/ncs/zephyr/include -Izephyr/include/generated -I/home/k/ncs/zephyr/soc/arm/nordic_nrf/nrf52 -I/home/k/ncs/zephyr/subsys/settings/include -I/home/k/ncs/zephyr/subsys/bluetooth -I/home/k/ncs/nrf/include -I/home/k/ncs/nrf/lib/multithreading_lock/. -I/home/k/ncs/nrf/subsys/bluetooth/controller/. -I/home/k/ncs/zephyr/drivers/flash -I/home/k/ncs/modules/hal/cmsis/CMSIS/Core/Include -I/home/k/ncs/modules/hal/nordic/nrfx -I/home/k/ncs/modules/hal/nordic/nrfx/drivers/include -I/home/k/ncs/modules/hal/nordic/nrfx/mdk -I/home/k/ncs/zephyr/modules/hal_nordic/nrfx/. -I/home/k/ncs/modules/debug/segger/SEGGER -I/home/k/ncs/modules/debug/segger/Config -I/home/k/ncs/zephyr/modules/segger/. -I/home/k/ncs/modules/crypto/tinycrypt/lib/include -I/home/k/ncs/nrfxlib/mpsl/include -I/home/k/ncs/nrfxlib/mpsl/include/protocol -I/home/k/ncs/nrfxlib/softdevice_controller/include -isystem /home/k/ncs/zephyr/lib/libc/minimal/include -isystem /opt/gnuarmemb/bin/../lib/gcc/arm-none-eabi/10.3.1/include -isystem /opt/gnuarmemb/bin/../lib/gcc/arm-none-eabi/10.3.1/include-fixed -isystem /home/k/ncs/nrfxlib/crypto/nrf_cc310_platform/include -Os -imacros /home/k/ncs/nrf/samples/bluetooth/ncs-peripheral-uart-adc/build/zephyr/include/generated/autoconf.h -ffreestanding -fno-common -g -fdiagnostics-color=always -mcpu=cortex-m4 -mthumb -mabi=aapcs -imacros /home/k/ncs/zephyr/include/toolchain/zephyr_stdint.h -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wno-main -Wno-pointer-sign -Wpointer-arith -Wexpansion-to-defined -Wno-address-of-packed-member -Wno-unused-but-set-variable -Werror=implicit-int -fno-asynchronous-unwind-tables -fno-pie -fno-pic -fno-strict-overflow -fno-reorder-functions -fno-defer-pop -fmacro-prefix-map=/home/k/ncs/nrf/samples/bluetooth/ncs-peripheral-uart-adc=CMAKE_SOURCE_DIR -fmacro-prefix-map=/home/k/ncs/zephyr=ZEPHYR_BASE -fmacro-prefix-map=/home/k/ncs=WEST_TOPDIR -ffunction-sections -fdata-sections -std=c99 -nostdinc -MD -MT CMakeFiles/app.dir/src/main.c.obj -MF CMakeFiles/app.dir/src/main.c.obj.d -o CMakeFiles/app.dir/src/main.c.obj -c ../src/main.c
../src/main.c: In function 'uart_cb':
../src/main.c:160:4: warning: 'k_delayed_work_submit' is deprecated [-Wdeprecated-declarations]
  160 |    k_delayed_work_submit(&uart_work,
      |    ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/k/ncs/zephyr/include/zephyr.h:18,
                 from ../src/main.c:12:
/home/k/ncs/zephyr/include/kernel.h:3700:19: note: declared here
 3700 | static inline int k_delayed_work_submit(struct k_delayed_work *work,
      |                   ^~~~~~~~~~~~~~~~~~~~~
../src/main.c: In function 'uart_work_handler':
../src/main.c:220:3: warning: 'k_delayed_work_submit' is deprecated [-Wdeprecated-declarations]
  220 |   k_delayed_work_submit(&uart_work, UART_WAIT_FOR_BUF_DELAY);
      |   ^~~~~~~~~~~~~~~~~~~~~
In file included from /home/k/ncs/zephyr/include/zephyr.h:18,
                 from ../src/main.c:12:
/home/k/ncs/zephyr/include/kernel.h:3700:19: note: declared here
 3700 | static inline int k_delayed_work_submit(struct k_delayed_work *work,
      |                   ^~~~~~~~~~~~~~~~~~~~~
../src/main.c: In function 'uart_init':
../src/main.c:244:2: warning: 'k_delayed_work_init' is deprecated [-Wdeprecated-declarations]
  244 |  k_delayed_work_init(&uart_work, uart_work_handler);
      |  ^~~~~~~~~~~~~~~~~~~
In file included from /home/k/ncs/zephyr/include/zephyr.h:18,
                 from ../src/main.c:12:
/home/k/ncs/zephyr/include/kernel.h:3682:20: note: declared here
 3682 | static inline void k_delayed_work_init(struct k_delayed_work *work,
      |                    ^~~~~~~~~~~~~~~~~~~
In file included from /home/k/ncs/zephyr/include/sys/util_macro.h:34,
                 from /home/k/ncs/zephyr/include/sys/util.h:17,
                 from /home/k/ncs/zephyr/include/sched_priq.h:9,
                 from /home/k/ncs/zephyr/include/kernel_includes.h:23,
                 from /home/k/ncs/zephyr/include/kernel.h:17,
                 from /home/k/ncs/zephyr/include/zephyr.h:18,
                 from ../src/main.c:12:
../src/main.c: In function 'num_comp_reply':
/home/k/ncs/zephyr/include/sys/cbprintf_internal.h:88:15: error: invalid use of undefined type 'struct bt_conn'
   88 |  _Generic((x) + 0, \
        |                       ^
